-- MySQL Script generated by MySQL Workbench
-- Fri Feb  6 08:43:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecoShareDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecoShareDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoShareDB` DEFAULT CHARACTER SET utf8 ;
USE `ecoShareDB` ;

-- -----------------------------------------------------
-- Table `ecoShareDB`.`usario_doc_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`usario_doc_tipo` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`usario_doc_tipo` (
  `id` INT NOT NULL,
  `usario_doc_tipo_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`usuario` (
  `id` INT NOT NULL,
  `usuario_doc` VARCHAR(100) NULL,
  `usuario_doc_tipo_id` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `senha` VARCHAR(100) NOT NULL,
  INDEX `Doc_idx` (`usuario_doc_tipo_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_usuario_usuario_doc_tipo`
    FOREIGN KEY (`usuario_doc_tipo_id`)
    REFERENCES `ecoShareDB`.`usario_doc_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`endereco` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`endereco` (
  `usuario_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(250) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  PRIMARY KEY (`usuario_id`, `endereco_id`),
  UNIQUE INDEX `CEP_UNIQUE` (`CEP` ASC) VISIBLE,
  CONSTRAINT `FK_endereco_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`usuario_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`usuario_telefone` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`usuario_telefone` (
  `usuario_id` INT NOT NULL,
  `telefone_id` INT NOT NULL,
  `Telefone` VARCHAR(40) NULL,
  PRIMARY KEY (`usuario_id`, `telefone_id`),
  CONSTRAINT `FK_telefone_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`cupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`cupon` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`cupon` (
  `usuario_id` INT NOT NULL,
  `sorteio_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `sorteio_id`),
  CONSTRAINT `FK_cupon_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`item` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(45) NULL,
  `descricao` MEDIUMTEXT NULL,
  `nome` VARCHAR(200) NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `FK_item_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`item_novo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`item_novo` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`item_novo` (
  `item_id` INT NOT NULL,
  `estoque` INT NULL DEFAULT 1,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `FK_item_novo_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `ecoShareDB`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`item_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`item_status` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`item_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `item_statuscol` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL COMMENT 'Essa coluna vai guardas coisas do tipo 1 - disponível 2 - em manutenção 3 - emprestado',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`item_usado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`item_usado` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`item_usado` (
  `item_id` INT NOT NULL,
  `item_status_id` INT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `status_idx` (`item_status_id` ASC) VISIBLE,
  CONSTRAINT `FK_item_usasdo_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `ecoShareDB`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_item_usasdo_item_status`
    FOREIGN KEY (`item_status_id`)
    REFERENCES `ecoShareDB`.`item_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`manutencao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`manutencao` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`manutencao` (
  `item_id` INT NOT NULL,
  `manutencao_id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `laudo` VARCHAR(45) NULL,
  PRIMARY KEY (`manutencao_id`, `item_id`),
  INDEX `item_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `FK_manutencao_item_usado`
    FOREIGN KEY (`item_id`)
    REFERENCES `ecoShareDB`.`item_usado` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`anuncio_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`anuncio_tipo` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`anuncio_tipo` (
  `anuncio_tipo_id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`anuncio_tipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`anuncio` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`anuncio` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL,
  `iten_id` INT NULL,
  `valor_anuncio` INT NULL,
  `descricao` TEXT NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `item_idx` (`iten_id` ASC) VISIBLE,
  INDEX `tipo_idx` (`id` ASC, `tipo` ASC) VISIBLE,
  CONSTRAINT `FK_anuncio_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_anuncio_item`
    FOREIGN KEY (`iten_id`)
    REFERENCES `ecoShareDB`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_anuncio_anuncio_tipo`
    FOREIGN KEY (`id` , `tipo`)
    REFERENCES `ecoShareDB`.`anuncio_tipo` (`anuncio_tipo_id` , `anuncio_tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`formas_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`formas_pagamento` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`formas_pagamento` (
  `id` INT NOT NULL,
  `forma` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`registro_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`registro_tipo` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`registro_tipo` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`registro` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`registro` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL COMMENT 'Esse usuário é o comprador do anúncio',
  `anuncio_id` INT NULL,
  `data` DATE NULL,
  `forma_pagamento_id` INT NULL,
  `valor_registro` INT NULL,
  `registro_tipo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `comprador_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `comprado_idx` (`anuncio_id` ASC) VISIBLE,
  INDEX `forma de pagamento_idx` (`forma_pagamento_id` ASC) VISIBLE,
  INDEX `tipo_idx` (`registro_tipo_id` ASC) VISIBLE,
  CONSTRAINT `FK_registro_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_registro_anuncio`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `ecoShareDB`.`anuncio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_registro_forma_pagamento`
    FOREIGN KEY (`forma_pagamento_id`)
    REFERENCES `ecoShareDB`.`formas_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_registro_registro_tipo`
    FOREIGN KEY (`registro_tipo_id`)
    REFERENCES `ecoShareDB`.`registro_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`registro_troca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`registro_troca` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`registro_troca` (
  `registro_id` INT NOT NULL,
  `iten_recebido` INT NULL,
  PRIMARY KEY (`registro_id`),
  CONSTRAINT `FK_registro_troca_registro`
    FOREIGN KEY (`registro_id`)
    REFERENCES `ecoShareDB`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`registro_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`registro_venda` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`registro_venda` (
  `registro_id` INT NOT NULL,
  PRIMARY KEY (`registro_id`),
  CONSTRAINT `FK_registro_venda_registro`
    FOREIGN KEY (`registro_id`)
    REFERENCES `ecoShareDB`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`registro_emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`registro_emprestimo` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`registro_emprestimo` (
  `registro_id` INT NOT NULL,
  `data_previsao` DATE NULL,
  `data_entregue` DATE NULL,
  PRIMARY KEY (`registro_id`),
  CONSTRAINT `FK_registro_emprestimo_registro`
    FOREIGN KEY (`registro_id`)
    REFERENCES `ecoShareDB`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`atendimento_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`atendimento_status` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`atendimento_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`atendimento` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`atendimento` (
  `atendimento_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `protocolo` INT NOT NULL,
  `descricao` TEXT NULL,
  `atendimento_status_id` INT NOT NULL,
  `registro_id` INT NULL,
  PRIMARY KEY (`atendimento_id`),
  INDEX `status_idx` (`atendimento_status_id` ASC) VISIBLE,
  INDEX `usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `registro_idx` (`registro_id` ASC) VISIBLE,
  CONSTRAINT `FK_atendimento_atendimento_status`
    FOREIGN KEY (`atendimento_status_id`)
    REFERENCES `ecoShareDB`.`atendimento_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_atendimento_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_atendimento_registro`
    FOREIGN KEY (`registro_id`)
    REFERENCES `ecoShareDB`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`avaliacao_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`avaliacao_usuario` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`avaliacao_usuario` (
  `id` INT NOT NULL,
  `usuario1_id` INT NULL,
  `usuario2_id` INT NULL,
  `descricao` VARCHAR(200) NULL,
  `nota` INT NULL,
  `like` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `avaliador_idx` (`usuario1_id` ASC) VISIBLE,
  INDEX `avaliado_idx` (`usuario2_id` ASC) VISIBLE,
  CONSTRAINT `FK_avaliacao_usuario_usuario1`
    FOREIGN KEY (`usuario1_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_avaliacao_usuario_usuario2`
    FOREIGN KEY (`usuario2_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoShareDB`.`avaliacoes_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoShareDB`.`avaliacoes_item` ;

CREATE TABLE IF NOT EXISTS `ecoShareDB`.`avaliacoes_item` (
  `id` INT NOT NULL,
  `usuario1_id` INT NULL,
  `item_id` INT NULL,
  `descricao` VARCHAR(200) NULL,
  `nota` INT NULL,
  `like` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `avaliador_idx` (`usuario1_id` ASC) VISIBLE,
  INDEX `avaliado_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `FK_avaliacao_item_usuario`
    FOREIGN KEY (`usuario1_id`)
    REFERENCES `ecoShareDB`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_avaliacao_item_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `ecoShareDB`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
