-- MySQL Script generated by MySQL Workbench
-- Thu Feb  5 11:53:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usario_doc_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usario_doc_tipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usario_doc_tipo` (
  `id` INT NOT NULL,
  `usario_doc_tipo_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `usuario_doc` INT NULL,
  `usuario_doc_tipo_id` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `Doc_idx` (`usuario_doc_tipo_id` ASC) VISIBLE,
  CONSTRAINT `Doc`
    FOREIGN KEY (`usuario_doc_tipo_id`)
    REFERENCES `mydb`.`usario_doc_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_endereco` (
  `usuario_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(250) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  PRIMARY KEY (`usuario_id`, `endereco_id`),
  UNIQUE INDEX `CEP_UNIQUE` (`CEP` ASC) VISIBLE,
  CONSTRAINT `Usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_telefones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_telefones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_telefones` (
  `usuario_id` INT NOT NULL,
  `telefone_id` INT NOT NULL,
  `Telefone` VARCHAR(40) NULL,
  PRIMARY KEY (`usuario_id`, `telefone_id`),
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cupon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cupon` (
  `usuario_id` INT NOT NULL,
  `sorteio_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `sorteio_id`),
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `id` INT NOT NULL,
  `foto` VARCHAR(45) NULL,
  `desc` MEDIUMTEXT NULL,
  `nome` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_novo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_novo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item_novo` (
  `item_id` INT NOT NULL,
  `estoque` INT NULL DEFAULT 1,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `item_statuscol` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL COMMENT 'Essa coluna vai guardas coisas do tipo 1 - disponível 2 - em manutenção 3 - emprestado',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_usado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_usado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item_usado` (
  `item_id` INT NOT NULL,
  `item_status_id` INT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `status_idx` (`item_status_id` ASC) VISIBLE,
  CONSTRAINT `item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status`
    FOREIGN KEY (`item_status_id`)
    REFERENCES `mydb`.`item_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manutencao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`manutencao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`manutencao` (
  `item_id` INT NOT NULL,
  `manutencao_id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `laudo` VARCHAR(45) NULL,
  PRIMARY KEY (`manutencao_id`, `item_id`),
  INDEX `item_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `item`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item_usado` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anuncio_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`anuncio_tipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`anuncio_tipo` (
  `anuncio_tipo_id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`anuncio_tipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`anuncio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`anuncio` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL,
  `iten_id` INT NULL,
  `valor_anuncio` INT NULL,
  `desc` TEXT NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `item_idx` (`iten_id` ASC) VISIBLE,
  INDEX `tipo_idx` (`id` ASC, `tipo` ASC) VISIBLE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item`
    FOREIGN KEY (`iten_id`)
    REFERENCES `mydb`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo`
    FOREIGN KEY (`id` , `tipo`)
    REFERENCES `mydb`.`anuncio_tipo` (`anuncio_tipo_id` , `anuncio_tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formas_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`formas_pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`formas_pagamento` (
  `id` INT NOT NULL,
  `forma` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_tipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_tipo` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL COMMENT 'Esse usuário é o comprador do anúncio',
  `anuncio_id` INT NULL,
  `data` DATE NULL,
  `forma_pagamento_id` INT NULL,
  `valor_registro` INT NULL,
  `registro_tipo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `comprador_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `comprado_idx` (`anuncio_id` ASC) VISIBLE,
  INDEX `forma de pagamento_idx` (`forma_pagamento_id` ASC) VISIBLE,
  INDEX `tipo_idx` (`registro_tipo_id` ASC) VISIBLE,
  CONSTRAINT `comprador`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comprado`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `mydb`.`anuncio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `forma de pagamento`
    FOREIGN KEY (`forma_pagamento_id`)
    REFERENCES `mydb`.`formas_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo`
    FOREIGN KEY (`registro_tipo_id`)
    REFERENCES `mydb`.`registro_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_troca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_troca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_troca` (
  `registro_id` INT NOT NULL,
  `iten_recebido` INT NULL,
  PRIMARY KEY (`registro_id`),
  CONSTRAINT `Registro`
    FOREIGN KEY (`registro_id`)
    REFERENCES `mydb`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_venda` (
  `registro_id` INT NOT NULL,
  PRIMARY KEY (`registro_id`),
  CONSTRAINT `Registro0`
    FOREIGN KEY (`registro_id`)
    REFERENCES `mydb`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_emprestimo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_emprestimo` (
  `registro_id` INT NOT NULL,
  `data_previsao` DATE NULL,
  `data_entregue` DATE NULL,
  PRIMARY KEY (`registro_id`),
  CONSTRAINT `Registro1`
    FOREIGN KEY (`registro_id`)
    REFERENCES `mydb`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendimento_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atendimento_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atendimento_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atendimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atendimento` (
  `atendimento_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `protocolo` INT NOT NULL,
  `desc` TEXT NULL,
  `atendimento_status_id` INT NOT NULL,
  `registro_id` INT NULL,
  PRIMARY KEY (`atendimento_id`),
  INDEX `status_idx` (`atendimento_status_id` ASC) VISIBLE,
  INDEX `usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `registro_idx` (`registro_id` ASC) VISIBLE,
  CONSTRAINT `status`
    FOREIGN KEY (`atendimento_status_id`)
    REFERENCES `mydb`.`atendimento_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `registro`
    FOREIGN KEY (`registro_id`)
    REFERENCES `mydb`.`registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacoes_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avaliacoes_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avaliacoes_usuario` (
  `id` INT NOT NULL,
  `usuario1_id` INT NULL,
  `usuario2_id` INT NULL,
  `desc` VARCHAR(200) NULL,
  `nota` INT NULL,
  `like` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `avaliador_idx` (`usuario1_id` ASC) VISIBLE,
  INDEX `avaliado_idx` (`usuario2_id` ASC) VISIBLE,
  CONSTRAINT `avaliador`
    FOREIGN KEY (`usuario1_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avaliado`
    FOREIGN KEY (`usuario2_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacoes_usuario_copy1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avaliacoes_usuario_copy1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avaliacoes_usuario_copy1` (
  `id` INT NOT NULL,
  `usuario1_id` INT NULL,
  `item_id` INT NULL,
  `desc` VARCHAR(200) NULL,
  `nota` INT NULL,
  `like` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `avaliador_idx` (`usuario1_id` ASC) VISIBLE,
  INDEX `avaliado_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `avaliador`
    FOREIGN KEY (`usuario1_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avaliado`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
